import React from "react";
import { Composition } from "remotion";
import { MainComposition } from "./MainComposition";
import { VideoPlayer } from "./Video";
import data from "./composition-data.json";
import samplePlan from "./data/sampleVideoPlan.json";
import type { VideoPlan } from "./types/video";

// ── Timing constants shared with MainComposition ───────────────────────────────
const FPS          = 30;
const TITLE_FRAMES = 5 * FPS;   // 5-second title card
const END_FRAMES   = 8 * FPS;   // 8-second end screen
const SHOT_FRAMES  = 3 * FPS;   // each shot is 3 seconds

const videoFrames = data.shots.length * SHOT_FRAMES;
const totalFrames = TITLE_FRAMES + videoFrames + END_FRAMES;

// ── Root ──────────────────────────────────────────────────────────────────────

export const RemotionRoot: React.FC = () => (
  <>
    {/**
     * ── Composition 1: MainComposition (branded overlay pipeline) ────────────
     * Original mode — renders final_animation.mp4 with branding overlays.
     * Input data: composition-data.json (generated by apply_motion_graphics.py)
     *
     * Render:
     *   npx remotion render src/index.ts MainComposition output.mp4
     */}
    <Composition
      id="MainComposition"
      component={MainComposition}
      durationInFrames={totalFrames}
      fps={FPS}
      width={1920}
      height={1080}
    />

    {/**
     * ── Composition 2: VideoComposition (scene-based motion graphics) ────────
     * New mode — renders a full video from a VideoPlan JSON.
     * No underlying video file required; all visuals are Remotion components.
     *
     * Default data: src/data/sampleVideoPlan.json
     * Override at render time via --props='{"plan":[...]}'
     *
     * Render with defaults:
     *   npx remotion render src/index.ts VideoComposition output.mp4
     *
     * Render with custom plan:
     *   npx remotion render src/index.ts VideoComposition output.mp4 \
     *     --props='{"plan": [{"scene_number":1,"duration":5,...}]}'
     *
     * Duration is computed dynamically from the plan via calculateMetadata.
     */}
    <Composition
      id="VideoComposition"
      component={VideoPlayer}
      fps={FPS}
      width={1920}
      height={1080}
      defaultProps={{ plan: samplePlan as unknown as VideoPlan }}
      calculateMetadata={({ props }) => ({
        durationInFrames: Math.max(
          FPS,
          (props.plan as VideoPlan).reduce(
            (acc, scene) => acc + Math.max(1, Math.round(scene.duration * FPS)),
            0
          )
        ),
      })}
    />
  </>
);
